### PR TITLE
Speed up `compute_unl()`, retire mpmath.

### PR DESCRIPTION
**Pull request by mwallerb**
This PR transitions the computation of `unl`, i.e., the transformation matrix from the IR basis to Matsubara frequencies from a mpmath based approach to a stabilized double precision calculation.

The values agree with the old code to ~ 3 ulp (`6e-16`)  (a naive algorithm is found to have deviations up to ~ 100 ulp, which messes up quantum chemistry calculations).  This slight loss of accuracy allows the code however to be about a factor of 7 faster, and the computation of sampling frequencies is even faster due to a new parameter.

Due to the slight regression in accuracy, I had to relax the unit test somewhat.

### CODE REVIEW

**Comment by shinaoka** [comment]
Thank you.
Amazing accuracy only with double precision arithmetic!
One minor issue: I've fixed one of sample files.

Relative errors must be small for stable quantum chemistry calculations (especially at high frequencies).
Could you reintroduce the tails?

```
max. absdiff = 7.007e-16, rel = 0.007898
````

**Comment by mwallerb** [comment]
@shinaoka Thanks for the pointer. I have reintroduced the tails with a semi-empirical bound for the start of the asymptotic region.

I have also re-activated the relative accuracy test, and everything seems to be working.

**Comment by mwallerb** [comment]
By the way, do we still need the `future` dependency?

**Comment by shinaoka** [comment]
Thanks!
Yes, "I" still have a Python 2.7 environment in my cluster.
Shall we bump the version to 2.2.0?

**Comment by mwallerb** [comment]
Yes, sure!  First merge, then bump, or you wanna do it the other way around?

**Pull request merged**
