### PR TITLE
Add vectorized calls for u[l](x) and v[l](y)

### PR DESCRIPTION
**Pull request by mwallerb**
- Add class _PiecewiseLegendrePoly, which represents the way
   the basis fucntion are currently stored in the HDF5 file,
   as well as exposing methods for evaluating these polynomials
   at a vector-valued x.

 - Moved basis.ulx(), basis.vly(), etc. methods to use the
   new infrastructure.

### CODE REVIEW

**Comment by shinaoka** [comment]
Great!
Shall we bump the version number to 2.1.0 (in setup.py)?

**Comment by mwallerb** [comment]
> Shall we bump the version number to 2.1.0 (in setup.py)?

Good idea. Done.

One question: do we want to make the piecewise polynomial representation part of the public API?
 - Pro: I have found myself extracting the `_ulx_*` quantities and especially `_sl`  and work with them, and people may find other ways to use the basis
 - Contra:  with a vectorized API that may not be that big of a deal, and it makes it harder to change the internal representation.  In this case, I think may want to vectorize basis.sl() as well.

**Comment by shinaoka** [comment]
I vote for vectorizing sl() and keeping the piecewise polynomial representation private for the moment.
We may change the internal representation in future.
But, I have no strong preferences.

**Comment by mwallerb** [comment]
@shinaoka : Ok, I added  vectorization for sl() and also added a unit test.

**Comment by shinaoka** [comment]
I've uploaded v2.1.0 to PyPI!

**Comment by mwallerb** [comment]
Yay! Thanks! :)

**Pull request merged**
